stan-core:
  stanPath: .stan
  excludes:
    - '**/.tsbuild/**'
    - '**/*.tsbuildinfo'
    - assets
    - CHANGELOG.md
    - docs
    - package-lock.json
    - 'test/**'
    - 'src/**/*.test.ts'
    - 'src/e2e/**'
  imports:
    '@commander-js/extra-typings':
      - node_modules/@commander-js/extra-typings/index.d.ts
    '@karmaniverous/smoz':
      - ../smoz/.stan/interop/get-dotenv/**
stan-cli:
  cliDefaults:
    run:
      facets: true
      plan: false
      sequential: true
  patchOpenCommand: code -g {file}
  scripts:
    typecheck: npm run typecheck
    lint: npm run lint:fix
    test: npm run test -- --no-color
    build:
      script: cross-env NO_COLOR=1 npm run build
      warnPattern: \\(!\\)(?!\\s+Circular dependencies\\s+node_modules)
    docs:
      script: npm run docs -- --emit none
      warnPattern: \\[warning\\]
    knip:
      script: npm run knip
      warnPattern: Configuration hints
    verify-types: npm run verify:types
    verify-smoke: npm run verify:smoke
    verify-package: npm run verify:package
    verify-bundle: npm run verify:bundle
    verify-tarball: npm run verify:tarball
